export { default as LandingPage } from './LandingPage'
export { default as LoginPage } from './LoginPage'
export { default as RegisterPage } from './RegisterPage'
export { default as DashboardPage } from './DashboardPage'
export { default as LeadsPage } from './LeadsPage'
export { default as LeadDetailPage } from './LeadDetailPage'
export { default as PipelinePage } from './PipelinePage'
export { default as FollowUpsPage } from './FollowUpsPage'
export { default as ContactsPage } from './ContactsPage'
export { default as InboxPage } from './InboxPage'
export { default as AutomationsPage } from './AutomationsPage'
export { default as IntegrationsPage } from './IntegrationsPage'
export { default as TeamPage } from './TeamPage'
export { default as SettingsPage } from './SettingsPage'
export { default as BillingPage } from './BillingPage'
export { default as TodayPage } from './TodayPage'
export { default as CopilotPage } from './CopilotPage'
export { default as AnalyticsPage } from './AnalyticsPage'
export { default as OnboardingPage } from './OnboardingPage'

// Marketing Subpages
export { default as ServicesPage } from './marketing/ServicesPage'
export { default as HowItWorksPage } from './marketing/HowItWorksPage'
export { default as PricingPage } from './marketing/PricingPage'
export { default as IntegrationsShowcasePage } from './marketing/IntegrationsShowcasePage'
export { default as PrivacyPage } from './marketing/PrivacyPage'
export { default as TermsPage } from './marketing/TermsPage'
export { default as CookiesPage } from './marketing/CookiesPage'
export { default as RefundPolicyPage } from './marketing/RefundPolicyPage'
export { default as SupportPage } from './marketing/SupportPage'

// Super Admin Pages
export { default as AdminLayout } from './admin/AdminLayout'
export { default as AdminDashboardPage } from './admin/AdminDashboardPage'
export { default as AdminOrganizationsPage } from './admin/AdminOrganizationsPage'
export { default as AdminSubscriptionsPage } from './admin/AdminSubscriptionsPage'
export { default as AdminUsagePage } from './admin/AdminUsagePage'
export { default as AdminSupportPage } from './admin/AdminSupportPage'
export { default as AdminFeatureFlagsPage } from './admin/AdminFeatureFlagsPage'
export { default as AdminSystemHealthPage } from './admin/AdminSystemHealthPage'
export { default as AdminAuditLogsPage } from './admin/AdminAuditLogsPage'
