// In-memory mock data provider for zero-config offline/demo fallback

export const mockLeads = [
  {
    _id: 'lead-001',
    name: 'Priya Sharma',
    contactId: {
      _id: 'cont-001',
      fullName: 'Priya Sharma',
      email: 'priya@techstartup.in',
      phone: '+91 98201 11223',
      company: 'TechStartup India',
      city: 'Bengaluru',
    },
    serviceRequired: 'E-commerce Redesign & WhatsApp Automation',
    source: 'whatsapp',
    status: 'qualified',
    leadScore: 92,
    aiScore: 92,
    leadTemperature: 'hot',
    estimatedValue: 120000,
    dealValue: 120000,
    currency: 'INR',
    lastContactAt: new Date(Date.now() - 3600000 * 2),
    createdAt: new Date(Date.now() - 86400000 * 1),
    aiAnalysis: {
      intent: 'Immediate redesign with budget allocated',
      urgencyScore: 95,
      keyNeeds: ['Shopify to Next.js migration', 'Automated abandoned cart WhatsApp recovery', 'Payment gateway integration'],
      sentiment: 'Highly enthusiastic',
      recommendedAction: 'Schedule technical scope discovery call within 2 hours',
      nextFollowUpDate: new Date(Date.now() + 86400000 * 1),
    },
  },
  {
    _id: 'lead-002',
    name: 'Rohan Mehta',
    contactId: {
      _id: 'cont-002',
      fullName: 'Rohan Mehta',
      email: 'rohan@apexlogistics.com',
      phone: '+91 98112 33445',
      company: 'Apex Global Logistics',
      city: 'Mumbai',
    },
    serviceRequired: 'Enterprise SEO & Lead Generation Funnel',
    source: 'website',
    status: 'proposal',
    leadScore: 84,
    aiScore: 84,
    leadTemperature: 'hot',
    estimatedValue: 240000,
    dealValue: 240000,
    currency: 'INR',
    lastContactAt: new Date(Date.now() - 3600000 * 5),
    createdAt: new Date(Date.now() - 86400000 * 3),
    aiAnalysis: {
      intent: 'Reviewing 3 agency proposals for Q2 marketing kickoff',
      urgencyScore: 80,
      keyNeeds: ['B2B SEO rankings', 'LinkedIn ads funnel', 'Conversion rate optimization'],
      sentiment: 'Evaluative and discerning',
      recommendedAction: 'Send case study on 4.2x ROI for logistics client',
    },
  },
  {
    _id: 'lead-003',
    name: 'Sarah Jenkins',
    contactId: {
      _id: 'cont-003',
      fullName: 'Sarah Jenkins',
      email: 'sarah@beaconhealth.co',
      phone: '+1 415 555 0192',
      company: 'Beacon Health Partners',
      city: 'San Francisco',
    },
    serviceRequired: 'Custom Patient Intake Portal & CRM Integration',
    source: 'email',
    status: 'negotiation',
    leadScore: 88,
    aiScore: 88,
    leadTemperature: 'hot',
    estimatedValue: 450000,
    dealValue: 450000,
    currency: 'USD',
    lastContactAt: new Date(Date.now() - 3600000 * 8),
    createdAt: new Date(Date.now() - 86400000 * 5),
    aiAnalysis: {
      intent: 'Final contract terms negotiation with VP of Operations',
      urgencyScore: 88,
      keyNeeds: ['HIPAA compliant follow-up', 'Twilio SMS notifications', 'Custom dashboard'],
      sentiment: 'Warm, ready to close',
      recommendedAction: 'Confirm 10% annual billing discount to finalize signature',
    },
  },
  {
    _id: 'lead-004',
    name: 'Amitabh Verma',
    contactId: {
      _id: 'cont-004',
      fullName: 'Amitabh Verma',
      email: 'amitabh@vermarealty.in',
      phone: '+91 99203 44556',
      company: 'Verma Luxury Properties',
      city: 'Delhi NCR',
    },
    serviceRequired: 'Meta Ads & WhatsApp Fast-Lead Routing',
    source: 'facebook',
    status: 'contacted',
    leadScore: 68,
    aiScore: 68,
    leadTemperature: 'warm',
    estimatedValue: 90000,
    dealValue: 90000,
    currency: 'INR',
    lastContactAt: new Date(Date.now() - 3600000 * 18),
    createdAt: new Date(Date.now() - 86400000 * 2),
    aiAnalysis: {
      intent: 'Exploring automated lead response to beat competitor brokers',
      urgencyScore: 65,
      keyNeeds: ['Sub-2 minute response to Facebook lead ads', 'Agent assignment', 'Brochure sending via WhatsApp'],
      sentiment: 'Curious',
      recommendedAction: 'Trigger Day 2 value sequence',
    },
  },
  {
    _id: 'lead-005',
    name: 'Elena Rostova',
    contactId: {
      _id: 'cont-005',
      fullName: 'Elena Rostova',
      email: 'elena@novacreative.io',
      phone: '+44 20 7946 0912',
      company: 'Nova Creative Studio',
      city: 'London',
    },
    serviceRequired: 'AI Follow-up SaaS Setup for 15 Client Accounts',
    source: 'instagram',
    status: 'won',
    leadScore: 96,
    aiScore: 96,
    leadTemperature: 'hot',
    estimatedValue: 350000,
    dealValue: 350000,
    currency: 'INR',
    lastContactAt: new Date(Date.now() - 3600000 * 24),
    createdAt: new Date(Date.now() - 86400000 * 12),
    aiAnalysis: {
      intent: 'Deal won! Onboarding session scheduled.',
      urgencyScore: 100,
      sentiment: 'Delighted',
      recommendedAction: 'Send onboarding welcome pack and invite team to portal',
    },
  },
  {
    _id: 'lead-006',
    name: 'Vikram Singhania',
    contactId: {
      _id: 'cont-006',
      fullName: 'Vikram Singhania',
      email: 'vikram@singhaniagroup.com',
      phone: '+91 97110 55667',
      company: 'Singhania Industrial Group',
      city: 'Pune',
    },
    serviceRequired: 'B2B Cold Outreach & CRM Migration',
    source: 'linkedin',
    status: 'new',
    leadScore: 74,
    aiScore: 74,
    leadTemperature: 'warm',
    estimatedValue: 180000,
    dealValue: 180000,
    currency: 'INR',
    lastContactAt: new Date(Date.now() - 3600000 * 3),
    createdAt: new Date(Date.now() - 3600000 * 3),
    aiAnalysis: {
      intent: 'Inbound LinkedIn message asking about enterprise SLA',
      urgencyScore: 72,
      sentiment: 'Formal and professional',
      recommendedAction: 'Send introductory qualification questionnaire',
    },
  },
]

export const mockMessages = [
  {
    _id: 'msg-001',
    body: 'Hi, we are looking for a complete redesign of our e-commerce store and need automated WhatsApp follow-ups for abandoned carts.',
    direction: 'inbound',
    channel: 'whatsapp',
    createdAt: new Date(Date.now() - 3600000 * 6),
    status: 'received',
  },
  {
    _id: 'msg-002',
    body: 'Hello Priya! Thanks for reaching out to BrightWeb Digital Agency. I saw your inquiry regarding the e-commerce redesign and WhatsApp cart recovery. We helped a similar brand recover 28% of abandoned checkouts in 30 days. When would be a good time for a 15-minute intro call?',
    direction: 'outbound',
    channel: 'whatsapp',
    createdAt: new Date(Date.now() - 3600000 * 5),
    status: 'delivered',
  },
  {
    _id: 'msg-003',
    body: 'That sounds impressive! Would tomorrow at 11:30 AM IST work for your team?',
    direction: 'inbound',
    channel: 'whatsapp',
    createdAt: new Date(Date.now() - 3600000 * 2),
    status: 'received',
  },
]

export const mockFollowUps = [
  {
    _id: 'task-001',
    leadId: mockLeads[0],
    title: 'Send Discovery Call Confirmation & Agenda',
    dueAt: new Date(Date.now() + 3600000 * 4),
    status: 'pending',
    channel: 'whatsapp',
    priority: 'high',
    suggestedMessage: 'Hi Priya, looking forward to our call tomorrow at 11:30 AM IST. Here is our Google Meet link: meet.google.com/abc-defg-hij',
  },
  {
    _id: 'task-002',
    leadId: mockLeads[1],
    title: 'Follow-up on Custom Proposal Sent',
    dueAt: new Date(Date.now() - 3600000 * 2),
    status: 'pending',
    channel: 'email',
    priority: 'high',
    suggestedMessage: 'Hi Rohan, hope you had a chance to review our SEO & Funnel proposal. Happy to hop on a 10-minute call to answer any questions from your leadership team.',
  },
  {
    _id: 'task-003',
    leadId: mockLeads[3],
    title: 'Day 3 Check-In for Real Estate Inquiries',
    dueAt: new Date(Date.now() + 86400000 * 1),
    status: 'pending',
    channel: 'whatsapp',
    priority: 'medium',
    suggestedMessage: 'Hi Amitabh, checking in to see if you would like to see a live demo of how our sub-2-minute WhatsApp lead router works for real estate ads?',
  },
]

export const mockAnalytics = {
  overview: {
    totalLeads: 142,
    leadsChange: 24.5,
    hotLeads: 38,
    conversionRate: 18.2,
    conversionRateChange: 3.4,
    pipelineValue: 2840000,
    pipelineValueChange: 15.8,
    avgResponseMinutes: 1.8,
    responseSpeedChange: -42.0,
    closedDealsValue: 980000,
  },
  leadsTrend: [
    { date: 'Jan 15', leads: 8, qualified: 3 },
    { date: 'Jan 22', leads: 14, qualified: 6 },
    { date: 'Jan 29', leads: 22, qualified: 11 },
    { date: 'Feb 05', leads: 28, qualified: 15 },
    { date: 'Feb 12', leads: 35, qualified: 19 },
    { date: 'Feb 19', leads: 42, qualified: 24 },
  ],
  leadsBySource: [
    { source: 'WhatsApp', count: 52, percentage: 37, color: '#22c55e' },
    { source: 'Website Forms', count: 41, percentage: 29, color: '#6366f1' },
    { source: 'Meta Lead Ads', count: 26, percentage: 18, color: '#3b82f6' },
    { source: 'Instagram DMs', count: 15, percentage: 11, color: '#ec4899' },
    { source: 'LinkedIn', count: 8, percentage: 5, color: '#0ea5e9' },
  ],
  conversionFunnel: [
    { stage: 'Inbound Inquiries', count: 142, conversionRate: 100 },
    { stage: 'AI Qualified (Score >= 65)', count: 98, conversionRate: 69 },
    { stage: 'Demo / Discovery Booked', count: 54, conversionRate: 55 },
    { stage: 'Proposal Presented', count: 32, conversionRate: 59 },
    { stage: 'Closed Won Deals', count: 18, conversionRate: 56 },
  ],
  revenueByMonth: [
    { month: 'Sep', revenue: 420000, forecast: 400000 },
    { month: 'Oct', revenue: 580000, forecast: 550000 },
    { month: 'Nov', revenue: 710000, forecast: 680000 },
    { month: 'Dec', revenue: 840000, forecast: 800000 },
    { month: 'Jan', revenue: 980000, forecast: 950000 },
    { month: 'Feb', revenue: 1150000, forecast: 1100000 },
  ],
  teamPerformance: [
    { name: 'Arjun Kapoor', role: 'Founder & Sales Lead', leadsHandled: 64, dealsWon: 11, winRate: 38.5, revenue: 640000 },
    { name: 'Sneha Patel', role: 'Senior Account Executive', leadsHandled: 48, dealsWon: 8, winRate: 33.3, revenue: 390000 },
    { name: 'Kavita Rao', role: 'Inbound SDR', leadsHandled: 30, dealsWon: 4, winRate: 25.0, revenue: 120000 },
  ],
}
