// In-memory mock data provider for zero-config offline/demo fallback

export const mockLeads = [
  {
    _id: 'lead-001',
    name: 'Priya Sharma',
    contactId: {
      _id: 'cont-001',
      fullName: 'Priya Sharma',
      email: 'priya@techstartup.in',
      phone: '+91 98201 11223',
      company: 'TechStartup India',
      city: 'Bengaluru',
    },
    serviceRequired: 'E-commerce Redesign & WhatsApp Automation',
    source: 'whatsapp',
    status: 'qualified',
    leadScore: 92,
    aiScore: 92,
    leadTemperature: 'hot',
    estimatedValue: 120000,
    dealValue: 120000,
    currency: 'INR',
    lastContactAt: new Date(Date.now() - 3600000 * 2),
    createdAt: new Date(Date.now() - 86400000 * 1),
    aiAnalysis: {
      intent: 'Immediate redesign with budget allocated',
      urgencyScore: 95,
      keyNeeds: ['Shopify to Next.js migration', 'Automated abandoned cart WhatsApp recovery', 'Payment gateway integration'],
      sentiment: 'Highly enthusiastic',
      recommendedAction: 'Schedule technical scope discovery call within 2 hours',
      nextFollowUpDate: new Date(Date.now() + 86400000 * 1),
    },
  },
  {
    _id: 'lead-002',
    name: 'Rohan Mehta',
    contactId: {
      _id: 'cont-002',
      fullName: 'Rohan Mehta',
      email: 'rohan@apexlogistics.com',
      phone: '+91 98112 33445',
      company: 'Apex Global Logistics',
      city: 'Mumbai',
    },
    serviceRequired: 'Enterprise SEO & Lead Generation Funnel',
    source: 'website',
    status: 'proposal',
    leadScore: 84,
    aiScore: 84,
    leadTemperature: 'hot',
    estimatedValue: 240000,
    dealValue: 240000,
    currency: 'INR',
    lastContactAt: new Date(Date.now() - 3600000 * 5),
    createdAt: new Date(Date.now() - 86400000 * 3),
    aiAnalysis: {
      intent: 'Reviewing 3 agency proposals for Q2 marketing kickoff',
      urgencyScore: 80,
      keyNeeds: ['B2B SEO rankings', 'LinkedIn ads funnel', 'Conversion rate optimization'],
      sentiment: 'Evaluative and discerning',
      recommendedAction: 'Send case study on 4.2x ROI for logistics client',
    },
  },
  {
    _id: 'lead-003',
    name: 'Sarah Jenkins',
    contactId: {
      _id: 'cont-003',
      fullName: 'Sarah Jenkins',
      email: 'sarah@beaconhealth.co',
      phone: '+1 415 555 0192',
      company: 'Beacon Health Partners',
      city: 'San Francisco',
    },
    serviceRequired: 'Custom Patient Intake Portal & CRM Integration',
    source: 'email',
    status: 'negotiation',
    leadScore: 88,
    aiScore: 88,
    leadTemperature: 'hot',
    estimatedValue: 450000,
    dealValue: 450000,
    currency: 'USD',
    lastContactAt: new Date(Date.now() - 3600000 * 8),
    createdAt: new Date(Date.now() - 86400000 * 5),
    aiAnalysis: {
      intent: 'Final contract terms negotiation with VP of Operations',
      urgencyScore: 88,
      keyNeeds: ['HIPAA compliant follow-up', 'Twilio SMS notifications', 'Custom dashboard'],
      sentiment: 'Warm, ready to close',
      recommendedAction: 'Confirm 10% annual billing discount to finalize signature',
    },
  },
  {
    _id: 'lead-004',
    name: 'Amitabh Verma',
    contactId: {
      _id: 'cont-004',
      fullName: 'Amitabh Verma',
      email: 'amitabh@vermarealty.in',
      phone: '+91 99203 44556',
      company: 'Verma Luxury Properties',
      city: 'Delhi NCR',
    },
    serviceRequired: 'Meta Ads & WhatsApp Fast-Lead Routing',
    source: 'facebook',
    status: 'contacted',
    leadScore: 68,
    aiScore: 68,
    leadTemperature: 'warm',
    estimatedValue: 90000,
    dealValue: 90000,
    currency: 'INR',
    lastContactAt: new Date(Date.now() - 3600000 * 18),
    createdAt: new Date(Date.now() - 86400000 * 2),
    aiAnalysis: {
      intent: 'Exploring automated lead response to beat competitor brokers',
      urgencyScore: 65,
      keyNeeds: ['Sub-2 minute response to Facebook lead ads', 'Agent assignment', 'Brochure sending via WhatsApp'],
      sentiment: 'Curious',
      recommendedAction: 'Trigger Day 2 value sequence',
    },
  },
  {
    _id: 'lead-005',
    name: 'Elena Rostova',
    contactId: {
      _id: 'cont-005',
      fullName: 'Elena Rostova',
      email: 'elena@novacreative.io',
      phone: '+44 20 7946 0912',
      company: 'Nova Creative Studio',
      city: 'London',
    },
    serviceRequired: 'AI Follow-up SaaS Setup for 15 Client Accounts',
    source: 'instagram',
    status: 'won',
    leadScore: 96,
    aiScore: 96,
    leadTemperature: 'hot',
    estimatedValue: 350000,
    dealValue: 350000,
    currency: 'INR',
    lastContactAt: new Date(Date.now() - 3600000 * 24),
    createdAt: new Date(Date.now() - 86400000 * 12),
    aiAnalysis: {
      intent: 'Deal won! Onboarding session scheduled.',
      urgencyScore: 100,
      sentiment: 'Delighted',
      recommendedAction: 'Send onboarding welcome pack and invite team to portal',
    },
  },
  {
    _id: 'lead-006',
    name: 'Vikram Singhania',
    contactId: {
      _id: 'cont-006',
      fullName: 'Vikram Singhania',
      email: 'vikram@singhaniagroup.com',
      phone: '+91 97110 55667',
      company: 'Singhania Industrial Group',
      city: 'Pune',
    },
    serviceRequired: 'B2B Cold Outreach & CRM Migration',
    source: 'linkedin',
    status: 'new',
    leadScore: 74,
    aiScore: 74,
    leadTemperature: 'warm',
    estimatedValue: 180000,
    dealValue: 180000,
    currency: 'INR',
    lastContactAt: new Date(Date.now() - 3600000 * 3),
    createdAt: new Date(Date.now() - 3600000 * 3),
    aiAnalysis: {
      intent: 'Inbound LinkedIn message asking about enterprise SLA',
      urgencyScore: 72,
      sentiment: 'Formal and professional',
      recommendedAction: 'Send introductory qualification questionnaire',
    },
  },
]

export const mockMessages = [
  {
    _id: 'msg-001',
    body: 'Hi, we are looking for a complete redesign of our e-commerce store and need automated WhatsApp follow-ups for abandoned carts.',
    direction: 'inbound',
    channel: 'whatsapp',
    createdAt: new Date(Date.now() - 3600000 * 6),
    status: 'received',
  },
  {
    _id: 'msg-002',
    body: 'Hello Priya! Thanks for reaching out to BrightWeb Digital Agency. I saw your inquiry regarding the e-commerce redesign and WhatsApp cart recovery. We helped a similar brand recover 28% of abandoned checkouts in 30 days. When would be a good time for a 15-minute intro call?',
    direction: 'outbound',
    channel: 'whatsapp',
    createdAt: new Date(Date.now() - 3600000 * 5),
    status: 'delivered',
  },
  {
    _id: 'msg-003',
    body: 'That sounds impressive! Would tomorrow at 11:30 AM IST work for your team?',
    direction: 'inbound',
    channel: 'whatsapp',
    createdAt: new Date(Date.now() - 3600000 * 2),
    status: 'received',
  },
]

export const mockFollowUps = [
  {
    _id: 'task-001',
    leadId: mockLeads[0],
    title: 'Send Discovery Call Confirmation & Agenda',
    dueAt: new Date(Date.now() + 3600000 * 4),
    status: 'pending',
    channel: 'whatsapp',
    priority: 'high',
    suggestedMessage: 'Hi Priya, looking forward to our call tomorrow at 11:30 AM IST. Here is our Google Meet link: meet.google.com/abc-defg-hij',
  },
  {
    _id: 'task-002',
    leadId: mockLeads[1],
    title: 'Follow-up on Custom Proposal Sent',
    dueAt: new Date(Date.now() - 3600000 * 2),
    status: 'pending',
    channel: 'email',
    priority: 'high',
    suggestedMessage: 'Hi Rohan, hope you had a chance to review our SEO & Funnel proposal. Happy to hop on a 10-minute call to answer any questions from your leadership team.',
  },
  {
    _id: 'task-003',
    leadId: mockLeads[3],
    title: 'Day 3 Check-In for Real Estate Inquiries',
    dueAt: new Date(Date.now() + 86400000 * 1),
    status: 'pending',
    channel: 'whatsapp',
    priority: 'medium',
    suggestedMessage: 'Hi Amitabh, checking in to see if you would like to see a live demo of how our sub-2-minute WhatsApp lead router works for real estate ads?',
  },
]

export const mockAnalytics = {
  overview: {
    totalLeads: 142,
    newLeads: 45,
    hotLeads: 38,
    qualifiedLeads: 98,
    wonDeals: 26,
    lostDeals: 12,
    pendingFollowUps: 14,
    overdueFollowUps: 3,
    pipelineValue: 2840000,
    avgLeadScore: 68,
    conversionRate: 18.2,
    wonRevenue: 980000,
    lostRevenue: 240000,
    unrespondedLeads: 8,
    leadsChange: 24.5,
    conversionRateChange: 3.4,
    pipelineValueChange: 15.8,
    avgResponseMinutes: 1.8,
    responseSpeedChange: -42.0,
    closedDealsValue: 980000,
  },
  leadsTrend: [
    { date: 'Jan 15', leads: 8, qualified: 3 },
    { date: 'Jan 22', leads: 14, qualified: 6 },
    { date: 'Jan 29', leads: 22, qualified: 11 },
    { date: 'Feb 05', leads: 28, qualified: 15 },
    { date: 'Feb 12', leads: 35, qualified: 19 },
    { date: 'Feb 19', leads: 42, qualified: 24 },
  ],
  leadsBySource: [
    { source: 'WhatsApp', count: 52, percentage: 37, color: '#22c55e' },
    { source: 'Website Forms', count: 41, percentage: 29, color: '#6366f1' },
    { source: 'Meta Lead Ads', count: 26, percentage: 18, color: '#3b82f6' },
    { source: 'Instagram DMs', count: 15, percentage: 11, color: '#ec4899' },
    { source: 'LinkedIn', count: 8, percentage: 5, color: '#0ea5e9' },
  ],
  conversionFunnel: [
    { stage: 'Inbound Inquiries', count: 142, conversionRate: 100 },
    { stage: 'AI Qualified (Score >= 65)', count: 98, conversionRate: 69 },
    { stage: 'Demo / Discovery Booked', count: 54, conversionRate: 55 },
    { stage: 'Proposal Presented', count: 32, conversionRate: 59 },
    { stage: 'Closed Won Deals', count: 18, conversionRate: 56 },
  ],
  revenueByMonth: [
    { month: 'Sep', revenue: 420000, forecast: 400000 },
    { month: 'Oct', revenue: 580000, forecast: 550000 },
    { month: 'Nov', revenue: 710000, forecast: 680000 },
    { month: 'Dec', revenue: 840000, forecast: 800000 },
    { month: 'Jan', revenue: 980000, forecast: 950000 },
    { month: 'Feb', revenue: 1150000, forecast: 1100000 },
  ],
  teamPerformance: [
    { name: 'Arjun Kapoor', role: 'Founder & Sales Lead', leadsHandled: 64, dealsWon: 11, winRate: 38.5, revenue: 640000 },
    { name: 'Sneha Patel', role: 'Senior Account Executive', leadsHandled: 48, dealsWon: 8, winRate: 33.3, revenue: 390000 },
    { name: 'Kavita Rao', role: 'Inbound SDR', leadsHandled: 30, dealsWon: 4, winRate: 25.0, revenue: 120000 },
  ],
}

export const mockTodayData = {
  greeting: 'Good morning, Arjun!',
  summaryText: "Here's what needs your attention right now.",
  stats: {
    urgentFollowUps: 4,
    revenueAtRisk: 450000,
    hotLeadsUncontacted: 3,
    meetingsToday: 2,
    closedDealsMonth: 18,
  },
  priorityActions: [
    {
      id: 'act-001',
      leadId: 'lead-001',
      name: 'Priya Sharma',
      company: 'TechStartup India',
      channel: 'whatsapp',
      score: 92,
      priorityScore: 98,
      type: 'reply_urgent',
      title: 'Reply to WhatsApp inquiry on abandoned cart redesign',
      dealValue: 120000,
      dueIn: 'Reply within 12 mins',
      aiReason: 'High intent prospect asked for proposal availability and budget is confirmed.',
      suggestedAction: 'Send Discovery Call Confirmation',
    },
    {
      id: 'act-002',
      leadId: 'lead-002',
      name: 'Rohan Mehta',
      company: 'Apex Global Logistics',
      channel: 'email',
      score: 84,
      priorityScore: 89,
      type: 'followup_due',
      title: 'Send case study on 4.2x ROI before leadership review',
      dealValue: 240000,
      dueIn: 'Due in 2 hours',
      aiReason: 'Reviewing 3 agency proposals today. Providing relevant proof now doubles win rate.',
      suggestedAction: 'Send Logistics Case Study',
    },
    {
      id: 'act-003',
      leadId: 'lead-003',
      name: 'Sarah Jenkins',
      company: 'Beacon Health Partners',
      channel: 'email',
      score: 88,
      priorityScore: 86,
      type: 'negotiation_close',
      title: 'Confirm 10% annual prepayment discount to close contract',
      dealValue: 450000,
      dueIn: 'Decision expected today',
      aiReason: 'VP Operations indicated willingness to sign if annual billing incentive is confirmed.',
      suggestedAction: 'Approve & Send Agreement',
    },
    {
      id: 'act-004',
      leadId: 'lead-004',
      name: 'Amitabh Verma',
      company: 'Verma Luxury Properties',
      channel: 'facebook',
      score: 68,
      priorityScore: 78,
      type: 'qualify_inbound',
      title: 'Dispatch Day 2 automated WhatsApp cadence',
      dealValue: 90000,
      dueIn: 'Overdue by 1 hour',
      aiReason: 'Facebook lead inquiry has not received brochure yet.',
      suggestedAction: 'Send Property Brochure',
    },
  ],
  revenueAtRisk: [
    {
      leadId: 'lead-003',
      name: 'Sarah Jenkins',
      company: 'Beacon Health Partners',
      value: 450000,
      reason: 'Contract sent 3 days ago with no follow-up touchpoint.',
      urgency: 'high',
    },
    {
      leadId: 'lead-002',
      name: 'Rohan Mehta',
      company: 'Apex Global Logistics',
      value: 240000,
      reason: 'Competitor proposal mentioned in last email.',
      urgency: 'medium',
    },
  ],
  leadDecay: [
    {
      leadId: 'lead-004',
      name: 'Amitabh Verma',
      company: 'Verma Luxury Properties',
      daysSilent: 4,
      lastScore: 78,
      currentScore: 68,
      recommended: 'Send low-friction question via WhatsApp to re-engage.',
    },
  ],
}

export const mockCopilotResponses = {
  'which leads should i contact today': {
    type: 'leads_list',
    text: "Here are your top 3 highest-priority leads requiring immediate contact based on intent, deal value, and response window:",
    leads: [
      { id: 'lead-001', name: 'Priya Sharma', company: 'TechStartup India', score: 92, reason: 'High-intent WhatsApp inquiry for e-commerce redesign. Awaiting your call confirmation.' },
      { id: 'lead-002', name: 'Rohan Mehta', company: 'Apex Global Logistics', score: 84, reason: 'Proposal sent 2 days ago. Competitor evaluation ongoing.' },
      { id: 'lead-003', name: 'Sarah Jenkins', company: 'Beacon Health Partners', score: 88, reason: 'Final contract negotiations. Closing this week.' },
    ],
    recommendedAction: 'Click to open lead thread or generate AI responses immediately.',
  },
  'show me leads that haven\'t been followed up with': {
    type: 'leads_list',
    text: "Found 2 high-value leads with no activity in over 48 hours:",
    leads: [
      { id: 'lead-004', name: 'Amitabh Verma', company: 'Verma Luxury Properties', score: 68, reason: 'Inbound Meta Lead ad received 4 days ago. Sequence paused.' },
      { id: 'lead-006', name: 'Vikram Singhania', company: 'Singhania Industrial Group', score: 74, reason: 'Enterprise inquiry on LinkedIn with no reply sent yet.' },
    ],
  },
  'which hot leads haven\'t replied': {
    type: 'leads_list',
    text: "1 hot lead is currently waiting on reply from their team:",
    leads: [
      { id: 'lead-002', name: 'Rohan Mehta', company: 'Apex Global Logistics', score: 84, reason: 'Sent proposal 48h ago. AI recommends soft check-in touchpoint.' },
    ],
  },
  'summarize today\'s sales activity': {
    type: 'summary',
    text: "Daily Sales Summary for BrightWeb Digital:\n• Inbound Leads: 6 active leads handled today\n• Follow-ups completed: 14 out of 18 scheduled\n• Pipeline Volume: ₹12,40,000 active qualified pipeline\n• Win Rate this month: 38.5%\n• Key Opportunity: Sarah Jenkins (Beacon Health) contract worth ₹4,50,000 expected to close today.",
  },
  'show me opportunities likely to close this month': {
    type: 'opportunities',
    text: "3 deals have a probability of 70%+ to close before month-end:",
    deals: [
      { name: 'Beacon Health Custom Intake', value: 450000, probability: 85, expectedRevenue: 382500, stage: 'Negotiation' },
      { name: 'Apex Logistics Funnel', value: 240000, probability: 70, expectedRevenue: 168000, stage: 'Proposal' },
      { name: 'TechStartup Redesign', value: 120000, probability: 60, expectedRevenue: 72000, stage: 'Qualified' },
    ],
    totalForecast: '₹6,22,500 weighted revenue',
  },
}

export const mockObjections = {
  price: {
    type: 'Price Sensitivity',
    detectedSnippet: 'Is there any discount or flexibility on the retainer cost?',
    recommendedStrategy: 'Reinforce proven ROI & past case studies before offering any contractual concession.',
    suggestedRebuttal: 'I completely understand budget considerations. Rather than cutting scope, our clients typically see a 3.4x ROI within 60 days which covers the investment. We could also offer a 10% prepayment benefit on annual terms.',
  },
  timing: {
    type: 'Timing / Next Quarter',
    detectedSnippet: 'We might need to push this project start to next quarter.',
    recommendedStrategy: 'Identify the cost of delay and offer a phased milestone kickoff.',
    suggestedRebuttal: 'Understood. Keep in mind that onboarding takes 2 weeks, so starting milestone 1 now ensures your funnel is live in time for your peak quarter without impacting your current bandwidth.',
  },
}

export const mockCampaigns = [
  {
    id: 'camp-001',
    name: 'Q1 Cold Lead Revival Cadence',
    targetAudience: 'Leads with no response for 30+ days (Score >= 50)',
    leadCount: 42,
    status: 'active',
    responseRate: 19.4,
    aiStrategy: 'Re-engagement via value-first educational asset rather than direct sales pitch.',
    templateMessage: 'Hi {{name}}, things move fast! We just helped a business in {{industry}} increase qualified leads by 40% with automated follow-ups. Is this still on your radar for this quarter?',
  },
  {
    id: 'camp-002',
    name: 'Post-Demo Closing Revival',
    targetAudience: 'Proposals sent with no decision after 14 days',
    leadCount: 18,
    status: 'draft',
    responseRate: 0,
    aiStrategy: 'Overcoming ghosting with an executive check-in from agency founder.',
    templateMessage: 'Hey {{name}}, wanted to check if you had any thoughts on the proposal or if priorities shifted? Happy to align scope to your exact timeline.',
  },
]

